apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: wnyde0sp9-go 
  janus-idp.io/tekton: wnyde0sp9-go
  backstage.io/kubernetes-id: wnyde0sp9-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: wnyde0sp9-go
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml